import os
from dataclasses import dataclass, field

from hydra.core.config_store import ConfigStore


# --- Callbacks ---
@dataclass
class ModelCheckpointConfig:
    """Configuration for model checkpointing."""

    _target_: str = "lightning.pytorch.callbacks.ModelCheckpoint"
    dirpath: str | None = "${paths.output_dir}/checkpoints"
    filename: str | None = None  # if None, defaults to '{epoch}-{step}'
    monitor: str | None = "val/aupr"
    verbose: bool = False
    save_last: bool = True
    save_top_k: int = 1
    mode: str = "max"
    auto_insert_metric_name: bool = False
    save_weights_only: bool = False
    every_n_train_steps: int | None = None
    train_time_interval: int | None = None
    every_n_epochs: int | None = None
    save_on_train_epoch_end: bool | None = None


@dataclass
class EarlyStoppingConfig:
    """Configuration for early stopping."""

    _target_: str = "lightning.pytorch.callbacks.EarlyStopping"
    monitor: str = "val/aupr"
    min_delta: float = 0.0
    patience: int = 10
    verbose: bool = False
    mode: str = "max"
    strict: bool = True
    check_finite: bool = True
    stopping_threshold: float | None = None
    divergence_threshold: float | None = None
    check_on_train_epoch_end: bool | None = None


@dataclass
class ModelSummaryConfig:
    """Configuration for model summary."""

    _target_: str = "lightning.pytorch.callbacks.RichModelSummary"
    max_depth: int = 1


@dataclass
class RichProgressBarConfig:
    """Configuration for rich progress bar."""

    _target_: str = "lightning.pytorch.callbacks.RichProgressBar"


@dataclass
class CallbackConfig:
    """Default configuration for callbacks."""

    defaults: list = field(
        default_factory=lambda: [
            {"/callbacks@model_checkpoint": "model_checkpoint"},
            {"/callbacks@early_stopping": "early_stopping"},
            {"/callbacks@model_summary": "model_summary"},
            {"/callbacks@rich_progress_bar": "rich_progress_bar"},
            "_self_",
        ]
    )


def register_callbacks() -> None:
    """Register callbacks in the config."""
    cs = ConfigStore.instance()
    cs.store(group="callbacks", name="model_checkpoint", node=ModelCheckpointConfig)
    cs.store(group="callbacks", name="early_stopping", node=EarlyStoppingConfig)
    cs.store(group="callbacks", name="model_summary", node=ModelSummaryConfig)
    cs.store(group="callbacks", name="rich_progress_bar", node=RichProgressBarConfig)
    cs.store(group="callbacks", name="default", node=CallbackConfig)


# --- Loggers ---
@dataclass
class CSVLoggerConfig:
    """Configuration for CSVLogger."""

    _target_: str = "lightning.pytorch.loggers.csv_logs.CSVLogger"
    save_dir: str = "${paths.output_dir}"
    name: str = "csv/"
    prefix: str = ""


@dataclass
class WandbLoggerConfig:
    """Configuration for WandbLogger."""

    _target_: str = "lightning.pytorch.loggers.wandb.WandbLogger"
    # name: "" # name of the run (normally generated by wandb)
    save_dir: str = "${paths.output_dir}"
    offline: bool = False
    id: str | None = None  # pass correct id to resume experiment!
    anonymous: bool | None = None  # enable anonymous logging
    project: str = field(default_factory=lambda: os.path.basename(os.environ.get("PROJECT_ROOT", ".")))
    log_model: bool = False  # upload lightning ckpts
    prefix: str = ""  # a string to put at the beginning of metric keys
    # entity: "" # it is recommended to set this through the WANDB_ENTITY environment variable
    group: str = ""
    job_type: str = ""
    tags: list[str] | None = None


@dataclass
class MultipleLoggerConfig:
    """Add multiple logger keys for config."""

    defaults: list = field(
        default_factory=lambda: [
            {"/logger@csv": "csv"},
            {"/logger@wandb": "wandb"},
            "_self_",
        ]
    )


def register_loggers() -> None:
    """Register loggers in the config."""
    cs = ConfigStore.instance()
    cs.store(group="logger", name="csv", node=CSVLoggerConfig)
    cs.store(group="logger", name="wandb", node=WandbLoggerConfig)
    cs.store(group="logger", name="multiple", node=MultipleLoggerConfig)


# --- Trainer ---
@dataclass
class BaseTrainerConfig:
    """Base trainer config."""

    _target_: str = "lightning.Trainer"

    default_root_dir: str = "${paths.output_dir}"

    min_epochs: int = 1  # prevents early stopping
    max_epochs: int = 50

    accelerator: str = "cpu"
    devices: int = 1

    # mixed precision for extra speed-up
    precision: int | str | None = None

    # perform a validation loop every N training epochs
    check_val_every_n_epoch: int | None = None

    # set True to ensure deterministic results
    # makes training slower but gives more reproducibility than just setting seeds
    deterministic: bool = False
    strategy: str = "auto"

    # reload dataloaders every N epochs
    reload_dataloaders_every_n_epochs: int = 0

    # default values for placeholder
    detect_anomaly: bool = False
    fast_dev_run: bool = False
    profiler: str | None = None


@dataclass
class CPUTrainerConfig(BaseTrainerConfig):
    """CPU trainer config."""

    accelerator: str = "cpu"
    devices: int = 1


@dataclass
class GPUTrainerConfig(BaseTrainerConfig):
    """GPU trainer config."""

    accelerator: str = "gpu"
    devices: int = 1


@dataclass
class DDPTrainerConfig(BaseTrainerConfig):
    """DDP trainer config."""

    accelerator: str = "gpu"
    devices: int = 2  # use all available GPUs
    strategy: str = "ddp"
    num_nodes: int = 1
    sync_batchnorm: bool = True


def register_trainers() -> None:
    """Register trainers in the config."""
    cs = ConfigStore.instance()
    cs.store(group="trainer", name="default", node=BaseTrainerConfig)
    cs.store(group="trainer", name="cpu", node=CPUTrainerConfig)
    cs.store(group="trainer", name="gpu", node=GPUTrainerConfig)
    cs.store(group="trainer", name="ddp", node=DDPTrainerConfig)


# register all configs
def register_training_configs() -> None:
    """Register all training configs."""
    register_callbacks()
    register_loggers()
    register_trainers()
