# @package _global_

defaults:
  - _self_
  - data: mnist
  - model: lit_mnist
  - model/encoder: cnn
  - model/head: mlp
  - callbacks: default
  - logger: null
  - trainer: default
  - paths: default
  - hydra: default

  - task: null
  - experiment: null
  - hparams_search: null
  - debug: null

task_name: "train"
tags: ["dev"]

mode: ???

ckpt_path: null
seed: 68
